# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gentleman.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 226)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downloadBtn.setGeometry(QtCore.QRect(480, 20, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.downloadBtn.setFont(font)
        self.downloadBtn.setObjectName("downloadBtn")
        self.urlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.urlInput.setGeometry(QtCore.QRect(50, 20, 380, 25))
        self.urlInput.setInputMask("")
        self.urlInput.setText("")
        self.urlInput.setObjectName("urlInput")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(50, 60, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.pageLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageLabel.setGeometry(QtCore.QRect(50, 90, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pageLabel.setFont(font)
        self.pageLabel.setObjectName("pageLabel")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(50, 120, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(50, 150, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setObjectName("errorLabel")
        self.showTitle = QtWidgets.QLabel(self.centralwidget)
        self.showTitle.setGeometry(QtCore.QRect(120, 60, 450, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showTitle.setFont(font)
        self.showTitle.setText("")
        self.showTitle.setObjectName("showTitle")
        self.showPages = QtWidgets.QLabel(self.centralwidget)
        self.showPages.setGeometry(QtCore.QRect(120, 90, 450, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showPages.setFont(font)
        self.showPages.setText("")
        self.showPages.setObjectName("showPages")
        self.showStatus = QtWidgets.QLabel(self.centralwidget)
        self.showStatus.setGeometry(QtCore.QRect(120, 120, 450, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showStatus.setFont(font)
        self.showStatus.setText("")
        self.showStatus.setObjectName("showStatus")
        self.showError = QtWidgets.QLabel(self.centralwidget)
        self.showError.setGeometry(QtCore.QRect(120, 150, 450, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.showError.setFont(font)
        self.showError.setText("")
        self.showError.setObjectName("showError")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 60, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 150, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 180, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.costLabel = QtWidgets.QLabel(self.centralwidget)
        self.costLabel.setGeometry(QtCore.QRect(50, 180, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.costLabel.setFont(font)
        self.costLabel.setObjectName("costLabel")
        self.showTimeCost = QtWidgets.QLabel(self.centralwidget)
        self.showTimeCost.setGeometry(QtCore.QRect(120, 180, 450, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.showTimeCost.setFont(font)
        self.showTimeCost.setText("")
        self.showTimeCost.setObjectName("showTimeCost")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.downloadBtn.setText(_translate("MainWindow", "Download"))
        self.urlInput.setPlaceholderText(_translate("MainWindow", "https://nhentai.net/g/279486/"))
        self.nameLabel.setText(_translate("MainWindow", "Title"))
        self.pageLabel.setText(_translate("MainWindow", "Pages"))
        self.statusLabel.setText(_translate("MainWindow", "Status"))
        self.errorLabel.setText(_translate("MainWindow", "Error"))
        self.label.setText(_translate("MainWindow", ":"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.label_3.setText(_translate("MainWindow", ":"))
        self.label_4.setText(_translate("MainWindow", ":"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.costLabel.setText(_translate("MainWindow", "Cost"))
